---

- hosts: all
  become: true
  tasks:

  - name: install apache and php packages
    # not apt change to package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}" 
      state: latest
      update_cache: yes