- name: install apache2 and php packages on ubuntu
  tags: apache,httpd,php
  package:
    name: 
      - "{{ apache_package_name }}" 
      - "{{ php_package_name}}"
    state: latest        

- name: start and enable apache service
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change email address for admin
  tags: apache,centos,httpd
  lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.com
  when: ansible_distribution == "Ubuntu"   
  # register: pizza
  notify: restart_apache

# - name: restart httpd (ubuntu)
#   tags: apache,apache2,ubuntu
#   service:
#       name: "{{ apache_service }}"
#       state: restarted
#   when: pizza.changed    

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644